package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * Acceso generated by hbm2java
 */
public class Acceso  implements java.io.Serializable {


     private String idAcceso;
     private String codPadre;
     private String descripcion;
     private String url;
     private Character estado;

    public Acceso() {
    }

	
    public Acceso(String idAcceso) {
        this.idAcceso = idAcceso;
    }
    public Acceso(String idAcceso, String codPadre, String descripcion, String url, Character estado) {
       this.idAcceso = idAcceso;
       this.codPadre = codPadre;
       this.descripcion = descripcion;
       this.url = url;
       this.estado = estado;
    }
   
    public String getIdAcceso() {
        return this.idAcceso;
    }
    
    public void setIdAcceso(String idAcceso) {
        this.idAcceso = idAcceso;
    }
    public String getCodPadre() {
        return this.codPadre;
    }
    
    public void setCodPadre(String codPadre) {
        this.codPadre = codPadre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
}


