package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * AccesoRol generated by hbm2java
 */
public class AccesoRol  implements java.io.Serializable {


     private AccesoRolId id;

    public AccesoRol() {
    }

    public AccesoRol(AccesoRolId id) {
       this.id = id;
    }
   
    public AccesoRolId getId() {
        return this.id;
    }
    
    public void setId(AccesoRolId id) {
        this.id = id;
    }




}


