package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * AccesoRolId generated by hbm2java
 */
public class AccesoRolId  implements java.io.Serializable {


     private String idRol;
     private String idAcceso;

    public AccesoRolId() {
    }

    public AccesoRolId(String idRol, String idAcceso) {
       this.idRol = idRol;
       this.idAcceso = idAcceso;
    }
   
    public String getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(String idRol) {
        this.idRol = idRol;
    }
    public String getIdAcceso() {
        return this.idAcceso;
    }
    
    public void setIdAcceso(String idAcceso) {
        this.idAcceso = idAcceso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AccesoRolId) ) return false;
		 AccesoRolId castOther = ( AccesoRolId ) other; 
         
		 return ( (this.getIdRol()==castOther.getIdRol()) || ( this.getIdRol()!=null && castOther.getIdRol()!=null && this.getIdRol().equals(castOther.getIdRol()) ) )
 && ( (this.getIdAcceso()==castOther.getIdAcceso()) || ( this.getIdAcceso()!=null && castOther.getIdAcceso()!=null && this.getIdAcceso().equals(castOther.getIdAcceso()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdRol() == null ? 0 : this.getIdRol().hashCode() );
         result = 37 * result + ( getIdAcceso() == null ? 0 : this.getIdAcceso().hashCode() );
         return result;
   }   


}


