package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * AlumnosInformeSeguridadId generated by hbm2java
 */
public class AlumnosInformeSeguridadId  implements java.io.Serializable {


     private String idAlumno;
     private String idinforme;

    public AlumnosInformeSeguridadId() {
    }

    public AlumnosInformeSeguridadId(String idAlumno, String idinforme) {
       this.idAlumno = idAlumno;
       this.idinforme = idinforme;
    }
   
    public String getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(String idAlumno) {
        this.idAlumno = idAlumno;
    }
    public String getIdinforme() {
        return this.idinforme;
    }
    
    public void setIdinforme(String idinforme) {
        this.idinforme = idinforme;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlumnosInformeSeguridadId) ) return false;
		 AlumnosInformeSeguridadId castOther = ( AlumnosInformeSeguridadId ) other; 
         
		 return ( (this.getIdAlumno()==castOther.getIdAlumno()) || ( this.getIdAlumno()!=null && castOther.getIdAlumno()!=null && this.getIdAlumno().equals(castOther.getIdAlumno()) ) )
 && ( (this.getIdinforme()==castOther.getIdinforme()) || ( this.getIdinforme()!=null && castOther.getIdinforme()!=null && this.getIdinforme().equals(castOther.getIdinforme()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdAlumno() == null ? 0 : this.getIdAlumno().hashCode() );
         result = 37 * result + ( getIdinforme() == null ? 0 : this.getIdinforme().hashCode() );
         return result;
   }   


}


