package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private String idAlumno;
     private String carrera;
     private String religion;
     private String codigo;
     private String idPersona;
     private String facultad;
     private String foto;

    public Alumnos() {
    }

	
    public Alumnos(String idAlumno, String idPersona) {
        this.idAlumno = idAlumno;
        this.idPersona = idPersona;
    }
    public Alumnos(String idAlumno, String carrera, String religion, String codigo, String idPersona, String facultad, String foto) {
       this.idAlumno = idAlumno;
       this.carrera = carrera;
       this.religion = religion;
       this.codigo = codigo;
       this.idPersona = idPersona;
       this.facultad = facultad;
       this.foto = foto;
    }
   
    public String getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(String idAlumno) {
        this.idAlumno = idAlumno;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


