package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * AlumnosInformeSeguridad generated by hbm2java
 */
public class AlumnosInformeSeguridad  implements java.io.Serializable {


     private AlumnosInformeSeguridadId id;

    public AlumnosInformeSeguridad() {
    }

    public AlumnosInformeSeguridad(AlumnosInformeSeguridadId id) {
       this.id = id;
    }
   
    public AlumnosInformeSeguridadId getId() {
        return this.id;
    }
    
    public void setId(AlumnosInformeSeguridadId id) {
        this.id = id;
    }




}


