package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * CentroTrabajo generated by hbm2java
 */
public class CentroTrabajo  implements java.io.Serializable {


     private String idCentroTrabajo;
     private String lugar;
     private String nombre;
     private String idUniversidad;

    public CentroTrabajo() {
    }

	
    public CentroTrabajo(String idCentroTrabajo, String idUniversidad) {
        this.idCentroTrabajo = idCentroTrabajo;
        this.idUniversidad = idUniversidad;
    }
    public CentroTrabajo(String idCentroTrabajo, String lugar, String nombre, String idUniversidad) {
       this.idCentroTrabajo = idCentroTrabajo;
       this.lugar = lugar;
       this.nombre = nombre;
       this.idUniversidad = idUniversidad;
    }
   
    public String getIdCentroTrabajo() {
        return this.idCentroTrabajo;
    }
    
    public void setIdCentroTrabajo(String idCentroTrabajo) {
        this.idCentroTrabajo = idCentroTrabajo;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getIdUniversidad() {
        return this.idUniversidad;
    }
    
    public void setIdUniversidad(String idUniversidad) {
        this.idUniversidad = idUniversidad;
    }




}


