package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Control generated by hbm2java
 */
public class Control  implements java.io.Serializable {


     private ControlId id;
     private Date fecha;
     private String semestre;

    public Control() {
    }

	
    public Control(ControlId id) {
        this.id = id;
    }
    public Control(ControlId id, Date fecha, String semestre) {
       this.id = id;
       this.fecha = fecha;
       this.semestre = semestre;
    }
   
    public ControlId getId() {
        return this.id;
    }
    
    public void setId(ControlId id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }




}


