package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DescripcionPastor generated by hbm2java
 */
public class DescripcionPastor  implements java.io.Serializable {


     private String idDescPast;
     private Date fecha;
     private String asunto;
     private String descripcion;
     private String idEmpleado;
     private String idFolder;
     private String idAlumno;

    public DescripcionPastor() {
    }

	
    public DescripcionPastor(String idDescPast) {
        this.idDescPast = idDescPast;
    }
    public DescripcionPastor(String idDescPast, Date fecha, String asunto, String descripcion, String idEmpleado, String idFolder, String idAlumno) {
       this.idDescPast = idDescPast;
       this.fecha = fecha;
       this.asunto = asunto;
       this.descripcion = descripcion;
       this.idEmpleado = idEmpleado;
       this.idFolder = idFolder;
       this.idAlumno = idAlumno;
    }
   
    public String getIdDescPast() {
        return this.idDescPast;
    }
    
    public void setIdDescPast(String idDescPast) {
        this.idDescPast = idDescPast;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(String idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getIdFolder() {
        return this.idFolder;
    }
    
    public void setIdFolder(String idFolder) {
        this.idFolder = idFolder;
    }
    public String getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(String idAlumno) {
        this.idAlumno = idAlumno;
    }




}


