package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String idEmpleado;
     private String profesion;
     private Character cargo;
     private String idPersona;
     private String idCentroTrabajo;
     private String area;
     private String foto;

    public Empleado() {
    }

	
    public Empleado(String idEmpleado, String idPersona, String idCentroTrabajo) {
        this.idEmpleado = idEmpleado;
        this.idPersona = idPersona;
        this.idCentroTrabajo = idCentroTrabajo;
    }
    public Empleado(String idEmpleado, String profesion, Character cargo, String idPersona, String idCentroTrabajo, String area, String foto) {
       this.idEmpleado = idEmpleado;
       this.profesion = profesion;
       this.cargo = cargo;
       this.idPersona = idPersona;
       this.idCentroTrabajo = idCentroTrabajo;
       this.area = area;
       this.foto = foto;
    }
   
    public String getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(String idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    public Character getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Character cargo) {
        this.cargo = cargo;
    }
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getIdCentroTrabajo() {
        return this.idCentroTrabajo;
    }
    
    public void setIdCentroTrabajo(String idCentroTrabajo) {
        this.idCentroTrabajo = idCentroTrabajo;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


