package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * Externo generated by hbm2java
 */
public class Externo  implements java.io.Serializable {


     private String idExterno;
     private String estado;
     private String idAlumno;
     private String direccionActual;
     private String referencia;

    public Externo() {
    }

	
    public Externo(String idExterno) {
        this.idExterno = idExterno;
    }
    public Externo(String idExterno, String estado, String idAlumno, String direccionActual, String referencia) {
       this.idExterno = idExterno;
       this.estado = estado;
       this.idAlumno = idAlumno;
       this.direccionActual = direccionActual;
       this.referencia = referencia;
    }
   
    public String getIdExterno() {
        return this.idExterno;
    }
    
    public void setIdExterno(String idExterno) {
        this.idExterno = idExterno;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(String idAlumno) {
        this.idAlumno = idAlumno;
    }
    public String getDireccionActual() {
        return this.direccionActual;
    }
    
    public void setDireccionActual(String direccionActual) {
        this.direccionActual = direccionActual;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }




}


