package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * Folder generated by hbm2java
 */
public class Folder  implements java.io.Serializable {


     private String idFolder;
     private String codFolder;
     private String nivel;
     private Character revison;
     private String idAlumno;

    public Folder() {
    }

	
    public Folder(String idFolder) {
        this.idFolder = idFolder;
    }
    public Folder(String idFolder, String codFolder, String nivel, Character revison, String idAlumno) {
       this.idFolder = idFolder;
       this.codFolder = codFolder;
       this.nivel = nivel;
       this.revison = revison;
       this.idAlumno = idAlumno;
    }
   
    public String getIdFolder() {
        return this.idFolder;
    }
    
    public void setIdFolder(String idFolder) {
        this.idFolder = idFolder;
    }
    public String getCodFolder() {
        return this.codFolder;
    }
    
    public void setCodFolder(String codFolder) {
        this.codFolder = codFolder;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public Character getRevison() {
        return this.revison;
    }
    
    public void setRevison(Character revison) {
        this.revison = revison;
    }
    public String getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(String idAlumno) {
        this.idAlumno = idAlumno;
    }




}


