package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * HistorialId generated by hbm2java
 */
public class HistorialId  implements java.io.Serializable {


     private String idEmpleado;
     private String idCentroTrabajo;

    public HistorialId() {
    }

    public HistorialId(String idEmpleado, String idCentroTrabajo) {
       this.idEmpleado = idEmpleado;
       this.idCentroTrabajo = idCentroTrabajo;
    }
   
    public String getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(String idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getIdCentroTrabajo() {
        return this.idCentroTrabajo;
    }
    
    public void setIdCentroTrabajo(String idCentroTrabajo) {
        this.idCentroTrabajo = idCentroTrabajo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HistorialId) ) return false;
		 HistorialId castOther = ( HistorialId ) other; 
         
		 return ( (this.getIdEmpleado()==castOther.getIdEmpleado()) || ( this.getIdEmpleado()!=null && castOther.getIdEmpleado()!=null && this.getIdEmpleado().equals(castOther.getIdEmpleado()) ) )
 && ( (this.getIdCentroTrabajo()==castOther.getIdCentroTrabajo()) || ( this.getIdCentroTrabajo()!=null && castOther.getIdCentroTrabajo()!=null && this.getIdCentroTrabajo().equals(castOther.getIdCentroTrabajo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEmpleado() == null ? 0 : this.getIdEmpleado().hashCode() );
         result = 37 * result + ( getIdCentroTrabajo() == null ? 0 : this.getIdCentroTrabajo().hashCode() );
         return result;
   }   


}


