package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private HistorialId id;
     private Date fechaIngreso;
     private Date fechaSalida;

    public Historial() {
    }

	
    public Historial(HistorialId id) {
        this.id = id;
    }
    public Historial(HistorialId id, Date fechaIngreso, Date fechaSalida) {
       this.id = id;
       this.fechaIngreso = fechaIngreso;
       this.fechaSalida = fechaSalida;
    }
   
    public HistorialId getId() {
        return this.id;
    }
    
    public void setId(HistorialId id) {
        this.id = id;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }




}


