package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * Incidencias generated by hbm2java
 */
public class Incidencias  implements java.io.Serializable {


     private String idIncidencia;
     private String idPermiso;
     private Character estado;
     private String descripcion;
     private String tipo;
     private String idEmpleado;
     private String idAlumno;

    public Incidencias() {
    }

	
    public Incidencias(String idIncidencia) {
        this.idIncidencia = idIncidencia;
    }
    public Incidencias(String idIncidencia, String idPermiso, Character estado, String descripcion, String tipo, String idEmpleado, String idAlumno) {
       this.idIncidencia = idIncidencia;
       this.idPermiso = idPermiso;
       this.estado = estado;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.idEmpleado = idEmpleado;
       this.idAlumno = idAlumno;
    }
   
    public String getIdIncidencia() {
        return this.idIncidencia;
    }
    
    public void setIdIncidencia(String idIncidencia) {
        this.idIncidencia = idIncidencia;
    }
    public String getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(String idPermiso) {
        this.idPermiso = idPermiso;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(String idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(String idAlumno) {
        this.idAlumno = idAlumno;
    }




}


