package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * IncidenciasPruebasDocumento generated by hbm2java
 */
public class IncidenciasPruebasDocumento  implements java.io.Serializable {


     private IncidenciasPruebasDocumentoId id;

    public IncidenciasPruebasDocumento() {
    }

    public IncidenciasPruebasDocumento(IncidenciasPruebasDocumentoId id) {
       this.id = id;
    }
   
    public IncidenciasPruebasDocumentoId getId() {
        return this.id;
    }
    
    public void setId(IncidenciasPruebasDocumentoId id) {
        this.id = id;
    }




}


