package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * IncidenciasPruebasDocumentoId generated by hbm2java
 */
public class IncidenciasPruebasDocumentoId  implements java.io.Serializable {


     private String idIncidencia;
     private String idpruebas;

    public IncidenciasPruebasDocumentoId() {
    }

    public IncidenciasPruebasDocumentoId(String idIncidencia, String idpruebas) {
       this.idIncidencia = idIncidencia;
       this.idpruebas = idpruebas;
    }
   
    public String getIdIncidencia() {
        return this.idIncidencia;
    }
    
    public void setIdIncidencia(String idIncidencia) {
        this.idIncidencia = idIncidencia;
    }
    public String getIdpruebas() {
        return this.idpruebas;
    }
    
    public void setIdpruebas(String idpruebas) {
        this.idpruebas = idpruebas;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IncidenciasPruebasDocumentoId) ) return false;
		 IncidenciasPruebasDocumentoId castOther = ( IncidenciasPruebasDocumentoId ) other; 
         
		 return ( (this.getIdIncidencia()==castOther.getIdIncidencia()) || ( this.getIdIncidencia()!=null && castOther.getIdIncidencia()!=null && this.getIdIncidencia().equals(castOther.getIdIncidencia()) ) )
 && ( (this.getIdpruebas()==castOther.getIdpruebas()) || ( this.getIdpruebas()!=null && castOther.getIdpruebas()!=null && this.getIdpruebas().equals(castOther.getIdpruebas()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdIncidencia() == null ? 0 : this.getIdIncidencia().hashCode() );
         result = 37 * result + ( getIdpruebas() == null ? 0 : this.getIdpruebas().hashCode() );
         return result;
   }   


}


