package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * InformeSeguridad generated by hbm2java
 */
public class InformeSeguridad  implements java.io.Serializable {


     private String idinforme;
     private String descInforme;
     private String lugar;
     private Date fecha;
     private Character confirmar;
     private String idEmpleado;
     private String idFolder;

    public InformeSeguridad() {
    }

	
    public InformeSeguridad(String idinforme) {
        this.idinforme = idinforme;
    }
    public InformeSeguridad(String idinforme, String descInforme, String lugar, Date fecha, Character confirmar, String idEmpleado, String idFolder) {
       this.idinforme = idinforme;
       this.descInforme = descInforme;
       this.lugar = lugar;
       this.fecha = fecha;
       this.confirmar = confirmar;
       this.idEmpleado = idEmpleado;
       this.idFolder = idFolder;
    }
   
    public String getIdinforme() {
        return this.idinforme;
    }
    
    public void setIdinforme(String idinforme) {
        this.idinforme = idinforme;
    }
    public String getDescInforme() {
        return this.descInforme;
    }
    
    public void setDescInforme(String descInforme) {
        this.descInforme = descInforme;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Character getConfirmar() {
        return this.confirmar;
    }
    
    public void setConfirmar(Character confirmar) {
        this.confirmar = confirmar;
    }
    public String getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(String idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getIdFolder() {
        return this.idFolder;
    }
    
    public void setIdFolder(String idFolder) {
        this.idFolder = idFolder;
    }




}


