package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * InternosCultosId generated by hbm2java
 */
public class InternosCultosId  implements java.io.Serializable {


     private String idInterno;
     private String idControl;
     private char turno;

    public InternosCultosId() {
    }

    public InternosCultosId(String idInterno, String idControl, char turno) {
       this.idInterno = idInterno;
       this.idControl = idControl;
       this.turno = turno;
    }
   
    public String getIdInterno() {
        return this.idInterno;
    }
    
    public void setIdInterno(String idInterno) {
        this.idInterno = idInterno;
    }
    public String getIdControl() {
        return this.idControl;
    }
    
    public void setIdControl(String idControl) {
        this.idControl = idControl;
    }
    public char getTurno() {
        return this.turno;
    }
    
    public void setTurno(char turno) {
        this.turno = turno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InternosCultosId) ) return false;
		 InternosCultosId castOther = ( InternosCultosId ) other; 
         
		 return ( (this.getIdInterno()==castOther.getIdInterno()) || ( this.getIdInterno()!=null && castOther.getIdInterno()!=null && this.getIdInterno().equals(castOther.getIdInterno()) ) )
 && ( (this.getIdControl()==castOther.getIdControl()) || ( this.getIdControl()!=null && castOther.getIdControl()!=null && this.getIdControl().equals(castOther.getIdControl()) ) )
 && (this.getTurno()==castOther.getTurno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdInterno() == null ? 0 : this.getIdInterno().hashCode() );
         result = 37 * result + ( getIdControl() == null ? 0 : this.getIdControl().hashCode() );
         result = 37 * result + this.getTurno();
         return result;
   }   


}


