package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * InternosCultos generated by hbm2java
 */
public class InternosCultos  implements java.io.Serializable {


     private InternosCultosId id;
     private Character asistencia;
     private Integer notaLimpieza;

    public InternosCultos() {
    }

	
    public InternosCultos(InternosCultosId id) {
        this.id = id;
    }
    public InternosCultos(InternosCultosId id, Character asistencia, Integer notaLimpieza) {
       this.id = id;
       this.asistencia = asistencia;
       this.notaLimpieza = notaLimpieza;
    }
   
    public InternosCultosId getId() {
        return this.id;
    }
    
    public void setId(InternosCultosId id) {
        this.id = id;
    }
    public Character getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(Character asistencia) {
        this.asistencia = asistencia;
    }
    public Integer getNotaLimpieza() {
        return this.notaLimpieza;
    }
    
    public void setNotaLimpieza(Integer notaLimpieza) {
        this.notaLimpieza = notaLimpieza;
    }




}


