package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private String idPermiso;
     private Character tipo;
     private Date fechaSalida;
     private Date fechaRegreso;
     private String lugar;
     private String motivo;
     private String regresoReal;
     private String idInterno;
     private String idEmpleado;
     private Character confirmacion;
     private String semestre;

    public Permisos() {
    }

	
    public Permisos(String idPermiso, String idInterno) {
        this.idPermiso = idPermiso;
        this.idInterno = idInterno;
    }
    public Permisos(String idPermiso, Character tipo, Date fechaSalida, Date fechaRegreso, String lugar, String motivo, String regresoReal, String idInterno, String idEmpleado, Character confirmacion, String semestre) {
       this.idPermiso = idPermiso;
       this.tipo = tipo;
       this.fechaSalida = fechaSalida;
       this.fechaRegreso = fechaRegreso;
       this.lugar = lugar;
       this.motivo = motivo;
       this.regresoReal = regresoReal;
       this.idInterno = idInterno;
       this.idEmpleado = idEmpleado;
       this.confirmacion = confirmacion;
       this.semestre = semestre;
    }
   
    public String getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(String idPermiso) {
        this.idPermiso = idPermiso;
    }
    public Character getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public Date getFechaRegreso() {
        return this.fechaRegreso;
    }
    
    public void setFechaRegreso(Date fechaRegreso) {
        this.fechaRegreso = fechaRegreso;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public String getRegresoReal() {
        return this.regresoReal;
    }
    
    public void setRegresoReal(String regresoReal) {
        this.regresoReal = regresoReal;
    }
    public String getIdInterno() {
        return this.idInterno;
    }
    
    public void setIdInterno(String idInterno) {
        this.idInterno = idInterno;
    }
    public String getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(String idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Character getConfirmacion() {
        return this.confirmacion;
    }
    
    public void setConfirmacion(Character confirmacion) {
        this.confirmacion = confirmacion;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }




}


