package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String idPersona;
     private String nombre;
     private String apellPat;
     private String dni;
     private Integer telefono;
     private String correo;
     private Character estado;
     private Character sexo;
     private String apellMat;
     private String usuario;
     private String password;

    public Persona() {
    }

	
    public Persona(String idPersona) {
        this.idPersona = idPersona;
    }
    public Persona(String idPersona, String nombre, String apellPat, String dni, Integer telefono, String correo, Character estado, Character sexo, String apellMat, String usuario, String password) {
       this.idPersona = idPersona;
       this.nombre = nombre;
       this.apellPat = apellPat;
       this.dni = dni;
       this.telefono = telefono;
       this.correo = correo;
       this.estado = estado;
       this.sexo = sexo;
       this.apellMat = apellMat;
       this.usuario = usuario;
       this.password = password;
    }
   
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellPat() {
        return this.apellPat;
    }
    
    public void setApellPat(String apellPat) {
        this.apellPat = apellPat;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public String getApellMat() {
        return this.apellMat;
    }
    
    public void setApellMat(String apellMat) {
        this.apellMat = apellMat;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


