package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * PruebasDocumento generated by hbm2java
 */
public class PruebasDocumento  implements java.io.Serializable {


     private String idpruebas;
     private String descripcion;
     private String urlPrueba;

    public PruebasDocumento() {
    }

	
    public PruebasDocumento(String idpruebas) {
        this.idpruebas = idpruebas;
    }
    public PruebasDocumento(String idpruebas, String descripcion, String urlPrueba) {
       this.idpruebas = idpruebas;
       this.descripcion = descripcion;
       this.urlPrueba = urlPrueba;
    }
   
    public String getIdpruebas() {
        return this.idpruebas;
    }
    
    public void setIdpruebas(String idpruebas) {
        this.idpruebas = idpruebas;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUrlPrueba() {
        return this.urlPrueba;
    }
    
    public void setUrlPrueba(String urlPrueba) {
        this.urlPrueba = urlPrueba;
    }




}


