package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * PruebasDocumentoFolderId generated by hbm2java
 */
public class PruebasDocumentoFolderId  implements java.io.Serializable {


     private String idpruebas;
     private String idFolder;

    public PruebasDocumentoFolderId() {
    }

    public PruebasDocumentoFolderId(String idpruebas, String idFolder) {
       this.idpruebas = idpruebas;
       this.idFolder = idFolder;
    }
   
    public String getIdpruebas() {
        return this.idpruebas;
    }
    
    public void setIdpruebas(String idpruebas) {
        this.idpruebas = idpruebas;
    }
    public String getIdFolder() {
        return this.idFolder;
    }
    
    public void setIdFolder(String idFolder) {
        this.idFolder = idFolder;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PruebasDocumentoFolderId) ) return false;
		 PruebasDocumentoFolderId castOther = ( PruebasDocumentoFolderId ) other; 
         
		 return ( (this.getIdpruebas()==castOther.getIdpruebas()) || ( this.getIdpruebas()!=null && castOther.getIdpruebas()!=null && this.getIdpruebas().equals(castOther.getIdpruebas()) ) )
 && ( (this.getIdFolder()==castOther.getIdFolder()) || ( this.getIdFolder()!=null && castOther.getIdFolder()!=null && this.getIdFolder().equals(castOther.getIdFolder()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdpruebas() == null ? 0 : this.getIdpruebas().hashCode() );
         result = 37 * result + ( getIdFolder() == null ? 0 : this.getIdFolder().hashCode() );
         return result;
   }   


}


