package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * PruebasDocumentoFolder generated by hbm2java
 */
public class PruebasDocumentoFolder  implements java.io.Serializable {


     private PruebasDocumentoFolderId id;

    public PruebasDocumentoFolder() {
    }

    public PruebasDocumentoFolder(PruebasDocumentoFolderId id) {
       this.id = id;
    }
   
    public PruebasDocumentoFolderId getId() {
        return this.id;
    }
    
    public void setId(PruebasDocumentoFolderId id) {
        this.id = id;
    }




}


