package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private String idRol;
     private String idPersona;
     private String rol;
     private Character estado;

    public Rol() {
    }

	
    public Rol(String idRol, String idPersona) {
        this.idRol = idRol;
        this.idPersona = idPersona;
    }
    public Rol(String idRol, String idPersona, String rol, Character estado) {
       this.idRol = idRol;
       this.idPersona = idPersona;
       this.rol = rol;
       this.estado = estado;
    }
   
    public String getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(String idRol) {
        this.idRol = idRol;
    }
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }




}


