package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sanciones generated by hbm2java
 */
public class Sanciones  implements java.io.Serializable {


     private String idSancion;
     private String sancion;
     private Date fechaInicio;
     private Date fechaFinal;
     private String evaluacion;
     private String idEmpleado;
     private String idFolder;
     private String idAlumno;

    public Sanciones() {
    }

	
    public Sanciones(String idSancion) {
        this.idSancion = idSancion;
    }
    public Sanciones(String idSancion, String sancion, Date fechaInicio, Date fechaFinal, String evaluacion, String idEmpleado, String idFolder, String idAlumno) {
       this.idSancion = idSancion;
       this.sancion = sancion;
       this.fechaInicio = fechaInicio;
       this.fechaFinal = fechaFinal;
       this.evaluacion = evaluacion;
       this.idEmpleado = idEmpleado;
       this.idFolder = idFolder;
       this.idAlumno = idAlumno;
    }
   
    public String getIdSancion() {
        return this.idSancion;
    }
    
    public void setIdSancion(String idSancion) {
        this.idSancion = idSancion;
    }
    public String getSancion() {
        return this.sancion;
    }
    
    public void setSancion(String sancion) {
        this.sancion = sancion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public String getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(String evaluacion) {
        this.evaluacion = evaluacion;
    }
    public String getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(String idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getIdFolder() {
        return this.idFolder;
    }
    
    public void setIdFolder(String idFolder) {
        this.idFolder = idFolder;
    }
    public String getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(String idAlumno) {
        this.idAlumno = idAlumno;
    }




}


