package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * Universidad generated by hbm2java
 */
public class Universidad  implements java.io.Serializable {


     private String idUniversidad;
     private String nombre;
     private String direccion;

    public Universidad() {
    }

	
    public Universidad(String idUniversidad) {
        this.idUniversidad = idUniversidad;
    }
    public Universidad(String idUniversidad, String nombre, String direccion) {
       this.idUniversidad = idUniversidad;
       this.nombre = nombre;
       this.direccion = direccion;
    }
   
    public String getIdUniversidad() {
        return this.idUniversidad;
    }
    
    public void setIdUniversidad(String idUniversidad) {
        this.idUniversidad = idUniversidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


