package org.mybatis.bu.domain;
// Generated 26/01/2016 12:18:34 PM by Hibernate Tools 4.3.1



/**
 * UsuarioAcceso generated by hbm2java
 */
public class UsuarioAcceso  implements java.io.Serializable {


     private UsuarioAccesoId id;
     private String fecha;

    public UsuarioAcceso() {
    }

	
    public UsuarioAcceso(UsuarioAccesoId id) {
        this.id = id;
    }
    public UsuarioAcceso(UsuarioAccesoId id, String fecha) {
       this.id = id;
       this.fecha = fecha;
    }
   
    public UsuarioAccesoId getId() {
        return this.id;
    }
    
    public void setId(UsuarioAccesoId id) {
        this.id = id;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


